# Adapted from both the deal.II "linux.yml" and Lethe "release.yml" workflow
# Credit goes to their respective authors

name: ci-release

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  N_JOBS: 4
  CTEST_OUTPUT_ON_FAILURE: 1
  CTEST_PARALLEL_LEVEL: 1

jobs:
  build:
    name: Build with (deal.II:${{ matrix.dealii_version }})
    runs-on: ubuntu-latest

    strategy:
      # Continue testing if tests on one version of deal.II fail
      fail-fast: false
      matrix:
        dealii_version: ["master-noble", "v9.7.1-noble"]

    container:
      image: dealii/dealii:${{ matrix.dealii_version }}
      # options: --user root

    steps:
      - uses: actions/checkout@v6

      - name: Configure and build release
      # On the deal.II's development branch, ReferenceCell is now templatized,
      # so add the relevant compile flag. This will be removed when the next
      # version releases, as we'll be able to test on the version number.
        run: |
          mkdir build && cd build
          cmake -D CMAKE_BUILD_TYPE=Release \
                -D ENABLE_TESTING=1 \
                -D DEAL_II_WITH_HP_IDENTITIES_BUG=1 \
                -D REFERENCE_CELL_WITH_TEMPLATE_PARAMETER=${{ matrix.dealii_version == 'master-noble' && '1' || '0' }} \
                .. \
                -G Ninja
          ninja -j ${{ env.N_JOBS }}

      # Run the serial tests in parallel 
      - name: Run serial tests in release
        run: |
          cd build
          ctest -V --output-on-failure -E "mpirun=[2-9]" -j ${{ env.N_JOBS }}

      # Run the parallel tests one at a time 
      - name: Run parallel tests in release
        run: |
          cd build
          # incompressible_ns_lambda/steady_cylinder_3d fails on 6 procs with a MUMPS -9 error,
          # possibly due to insufficient memory on the github runner
          ctest -V --output-on-failure -R "mpirun=[2-9]" -E "incompressible_ns_lambda/steady_cylinder_3d" -j 1